# Generated by Django 3.2.4 on 2021-10-31 16:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Вид услуг',
                'verbose_name_plural': 'Виды услуг',
            },
        ),
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('position', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=models.FloatField())),
                ('name', models.CharField(max_length=40)),
                ('working_start', models.TimeField()),
                ('working_end', models.TimeField()),
                ('type_of_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.typeofcompany')),
            ],
        ),
    ]
