# Generated by Django 3.2.4 on 2021-11-01 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20211101_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Звезды рейтинга',
            },
        ),
        migrations.CreateModel(
            name='UniquePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='D:/programs/django/service_map/service/unique_points')),
            ],
        ),
        migrations.AddField(
            model_name='carservice',
            name='Website',
            field=models.SlugField(default='https://google.com', unique=True),
        ),
        migrations.AddField(
            model_name='carservice',
            name='images',
            field=models.ImageField(default=123, upload_to='D:/programs/django/service_map/service/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carservice',
            name='unique_point',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='service.uniquepoint'),
            preserve_default=False,
        ),
    ]
