# Generated by Django 3.2.4 on 2021-11-01 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20211101_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('car_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.carservice')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ratingstar')),
            ],
            options={
                'verbose_name': 'Рейтинг',
            },
        ),
    ]
