# Generated by Django 3.2.4 on 2021-11-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='Website',
            field=models.URLField(null=True, unique=True),
        ),
    ]
