# Generated by Django 3.2.4 on 2021-11-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_carservice_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='images',
            field=models.ImageField(upload_to='imgs/'),
        ),
    ]
