# Generated by Django 3.2.4 on 2021-11-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_carservice_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquepoint',
            name='image',
            field=models.ImageField(upload_to='unique_points/'),
        ),
    ]
